#spring:
#  datasource:
#    username: root
#    password: Katasandi@019
#    url: jdbc:mysql://localhost:3306/spring_mysql_1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#        ddl-auto: create-drop
#    properties:
#        hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
